---
title: "plot.Rmd"
author: "Nick R. Bachelder"
date: "2023-11-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(dplyr)
library(gtsummary)
library(ggplot2)
library(plyr)
library(gganimate)
library(ggforce)
library(animation)
library(ggrepel)
library(tidyr)
library(ggpubr)
library(viridis)
library(gt)
library(gtExtras)
```

```{r}
games <- read.csv(here::here("data/nfl-big-data-bowl-2024/games.csv"))
players <- read.csv(here::here("data/nfl-big-data-bowl-2024/players.csv")) %>% 
  rowwise() %>% dplyr::mutate(height = as.numeric(sub("\\-.*", "", height))*12 + as.numeric(sub('.+-(.+)', '\\1', height))) %>% ungroup() %>%
  dplyr::select(displayName, nflId, height, weight, position)
plays <- read.csv(here::here("data/nfl-big-data-bowl-2024/plays.csv"))
tackles <- read.csv(here::here("data/nfl-big-data-bowl-2024/tackles.csv"))
tracking <- do.call(rbind, lapply(seq(1, 9), function(week) {read.csv(here::here(paste0("data/nfl-big-data-bowl-2024/tracking_a_week_", week, ".csv")))}))
contracts <- nflreadr::load_contracts(file_type = getOption("nflreadr.prefer", default = "rds"))
contracts <- contracts %>%
  group_by(player) %>%
  filter(year_signed == max(year_signed)) %>%
  ungroup() %>%
  dplyr::select(player, team, apy_cap_pct) %>% dplyr::rename(displayName = player)
```

```{r}
plot_marginal_contribution <- function(game_id, play_id) {
  pred_df <- read.csv(paste0("/Users/nickbachelder/Desktop/Personal Code/Kaggle/Tackles/", game_id, "_", play_id, ".csv")) %>% dplyr::select(-X) %>%
      mutate(x = as.numeric(x), y = as.numeric(y))
  pred_no_original <- pred_df %>% filter(omit != 0)
  all_frames <- unique(pred_no_original$frameId)
  max_prob <- max(pred_no_original$upper)
  min_prob <- min(pred_no_original$lower)
  saveGIF({for (i in min(all_frames):max(all_frames)) {
    pred_df_frame <- pred_no_original %>% filter(frameId == i)
    p <- pred_df_frame %>% dplyr::select(-y) %>% group_by(omit, x) %>% dplyr::summarise(lower = sum(lower), upper = sum(upper), prob = sum(prob)) %>% ungroup() %>% 
      mutate(omit = as.factor(omit)) %>%
      ggplot() + geom_ribbon(aes(x = x, ymin = lower, ymax = upper), fill = "grey70") + geom_line(aes(x = x, y = prob)) + facet_wrap(~omit, ncol = 1) + theme_void() +
      theme(axis.title.x = element_text(),  axis.text.x = element_text(),  axis.ticks.x = element_line(), axis.title.y = element_text()) + ylim(min_prob, max_prob)
    print(p)
    print(paste0("Frame ", i))
    ani.pause()}
    },movie.name="facet_zoom_2.gif",ani.width = 600, ani.height = 600)
}

plot_combine_play_contribution <- function(game_id, play_id) {
    pred_df <- read.csv(paste0("/Users/nickbachelder/Desktop/Personal Code/Kaggle/Tackles/", game_id, "_", play_id, ".csv")) %>% dplyr::select(-X) %>%
      mutate(x = as.numeric(x), y = as.numeric(y))
    play_df <- tracking %>% filter(gameId == game_id, playId == play_id) %>%
      dplyr::mutate(type = case_when(position %in% c("QB", "TE",  "WR", "G", "OLB", "RB", "C", "FB") ~ "offense", 
                               is.na(nflId) ~ "ball",
                               TRUE ~ "defense"))
    describe <- (plays %>% filter(gameId == game_id, playId == play_id))$playDescription[1]
    all_frames <- unique(play_df$frameId)
    max_p <- max(pred_df$prob)
    oopt = ani.options(interval = 1/10)
    saveGIF({for (i in min(all_frames):max(all_frames)) {
      play_df_frame <- play_df %>% filter(frameId == i)
      pred_df_frame <- pred_df %>% filter(frameId == i, omit == 0) 
      min_x = 10
      max_x = 110
      min_y = 0
      max_y = 54
      main <- ggplot() + geom_tile(data = pred_df_frame, aes(x = x, y = y, fill = prob), width = 10, height = 10)
      main <- main +
        scale_fill_gradient(low = "grey", high = "brown1", limits = c(0, max_p)) +
            geom_vline(aes(xintercept = seq(round_any(min_x, 5, f = floor), 
                                          round_any(max_x, 5, f = ceiling), by = 5)), 
                     color = 'white') +
          geom_segment(aes(x = seq(round_any(min_x, 5, f = floor), round_any(max_x, 5, f = ceiling), by = 1 ), 
                           y = rep(70.9 / 3 - 0.5, length(seq(round_any(min_x, 5, f = floor), 
                                                                 round_any(max_x, 5, f = ceiling), by = 1 )) ), 
                           xend = seq(round_any(min_x, 5, f = floor), round_any(max_x, 5, f = ceiling), by = 1 ), 
                           yend = rep(70.9 / 3 + 0.5, length(seq(round_any(min_x, 5, f = floor), 
                                                                 round_any(max_x, 5, f = ceiling), by = 1 ))) ), 
                       color = 'white') +
          geom_segment(aes(x = seq(round_any(min_x, 5, f = floor), round_any(max_x, 5, f = ceiling), by = 1 ), 
                           y = rep(70.8 / 3 + 18.5 / 3 - 0.5, length(seq(round_any(min_x, 5, f = floor), 
                                                                 round_any(max_x, 5, f = ceiling), by = 1 )) ), 
                           xend = seq(round_any(min_x, 5, f = floor), round_any(max_x, 5, f = ceiling), by = 1 ), 
                           yend = rep(70.8 / 3 + 18.5 / 3 + 0.5, length(seq(round_any(min_x, 5, f = floor), 
                                                                 round_any(max_x, 5, f = ceiling), by = 1 ))) ), 
                       color = 'white') + ylab("") + xlab("") + 
        geom_hline(yintercept = 0, color = 'white')  + geom_hline(yintercept = 54, color = 'white') + geom_vline(xintercept = 0, color = 'white') + 
        geom_vline(xintercept = 120, color = 'white')  + 
        geom_point(data = play_df_frame, aes(x = x, y = y, size = type, color = type, shape = type))  +
        scale_shape_manual(values = c(20, 18, 18)) +
        scale_size_manual(values = c(2, 5, 5)) +
        scale_color_manual(values = c("white", "cornflowerblue", "lightseagreen")) +
        labs(title = "Tackle Classifier Example", x = "", y = "", caption = describe) + xlim(0, 120) + ylim(0, 54) + theme_minimal() 
      plot_list <- list()
      all_omit <- (pred_df %>% filter(omit!=0))$omit %>% unique()
      iter <- 1
      max_z = max((pred_df %>% filter(frameId == i, omit != 0))$prob)
      min_z = max((pred_df %>% filter(frameId == i, omit != 0))$prob)
      for (id in all_omit) {
        play_df_frame <- play_df %>% filter(frameId == i) %>% filter(nflId == id | type == 'ball')
        name <- (play_df_frame %>% filter(nflId == id))$displayName[1]
        pred_df_frame <- pred_df %>% filter(frameId == i, omit == id) 
        p <- ggplot() + geom_tile(data = pred_df_frame, aes(x = x, y = y, fill = prob), width = 10, height = 10)  +
          scale_fill_gradient2(midpoint = 0, low = "blue", mid = "grey", high = "brown1", limits = c(min_z, max_z)) +
              geom_vline(aes(xintercept = seq(round_any(min_x, 5, f = floor), 
                                            round_any(max_x, 5, f = ceiling), by = 5)), 
                       color = 'white') +
            geom_segment(aes(x = seq(round_any(min_x, 5, f = floor), round_any(max_x, 5, f = ceiling), by = 1 ), 
                             y = rep(70.9 / 3 - 0.5, length(seq(round_any(min_x, 5, f = floor), 
                                                                   round_any(max_x, 5, f = ceiling), by = 1 )) ), 
                             xend = seq(round_any(min_x, 5, f = floor), round_any(max_x, 5, f = ceiling), by = 1 ), 
                             yend = rep(70.9 / 3 + 0.5, length(seq(round_any(min_x, 5, f = floor), 
                                                                   round_any(max_x, 5, f = ceiling), by = 1 ))) ), 
                         color = 'white') +
            geom_segment(aes(x = seq(round_any(min_x, 5, f = floor), round_any(max_x, 5, f = ceiling), by = 1 ), 
                             y = rep(70.8 / 3 + 18.5 / 3 - 0.5, length(seq(round_any(min_x, 5, f = floor), 
                                                                   round_any(max_x, 5, f = ceiling), by = 1 )) ), 
                             xend = seq(round_any(min_x, 5, f = floor), round_any(max_x, 5, f = ceiling), by = 1 ), 
                             yend = rep(70.8 / 3 + 18.5 / 3 + 0.5, length(seq(round_any(min_x, 5, f = floor), 
                                                                   round_any(max_x, 5, f = ceiling), by = 1 ))) ), 
                         color = 'white') + ylab("") + xlab("") + 
          geom_hline(yintercept = 0, color = 'white')  + geom_hline(yintercept = 54, color = 'white') + geom_vline(xintercept = 0, color = 'white') + 
          geom_vline(xintercept = 120, color = 'white') + xlim(0, 120) + ylim(0, 54)  +
          geom_point(data = play_df_frame, aes(x = x, y = y, size = type, color = type, shape = type))  +
          scale_shape_manual(values = c(20, 18, 18)) +
          scale_size_manual(values = c(2, 5, 5)) +
          scale_color_manual(values = c("white", "cornflowerblue", "lightseagreen")) + theme_void() + theme(legend.position = "none") + ggtitle(name)
        plot_list[[iter]] <- p
        iter = iter+1
      }
      arranged_plots <- ggarrange(plotlist = plot_list, ncol = 3, nrow = 4)
      arranged_plots2 <-ggarrange(plotlist = list(main, arranged_plots), ncol = 1, nrow = 2)
      print(arranged_plots2)
      print(paste0("Frame ", i))
      ani.pause()}
    },movie.name="facet_zoom_2.gif",ani.width = 600, ani.height = 600)
}

plot_features <- function(game_id, play_id) {
    features <- read.csv(paste0("/Users/nickbachelder/Desktop/Personal Code/Kaggle/Tackles/features_", game_id, "_", play_id, ".csv")) %>% 
      dplyr::select(-X) %>% dplyr::rename(y = x, x = y) %>% group_by(feature_num) %>%
      mutate(value = (value - min(value)) / max(value) - min(value)) %>% ungroup()
    play_df <- tracking %>% filter(gameId == game_id, playId == play_id) %>%
      dplyr::mutate(type = case_when(position %in% c("QB", "TE",  "WR", "G", "OLB", "RB", "C", "FB") ~ "offense", 
                               is.na(nflId) ~ "ball",
                               TRUE ~ "defense"))
    describe <- (plays %>% filter(gameId == game_id, playId == play_id))$playDescription[1]
    all_frames <- unique(play_df$frameId)
    oopt = ani.options(interval = 1/10)
    saveGIF({for (i in min(all_frames):max(all_frames)) {
      image_this_frame <- features %>% filter(frameId == i-min(all_frames)) 
      plot_list <- list()
      # Iterate over unique feature names and create heat maps
      iter = 1
      for (feature_name in unique(image_this_frame$feature_num))  {
        limits <- c(0, 0.01)
        if (feature_name == "Carrier Velocity" | feature_name ==  "Carrier Acceleration") {
          limits <- c(0, 0.005)
        }
        feature_data <- subset(image_this_frame, feature_num == feature_name) 
        if (!(feature_name == "Offense Position" | feature_name == "Defense Position")) {
          p <- ggplot() + ggtitle(feature_name) +
            geom_raster(data=feature_data, aes(x = x, y = y, fill = value),interpolate = TRUE) +
              geom_vline(aes(xintercept = seq(round_any(min_x, 5, f = floor), 
                                            round_any(max_x, 5, f = ceiling), by = 5)), 
                       color = 'white') +
            geom_segment(aes(x = seq(round_any(min_x, 5, f = floor), round_any(max_x, 5, f = ceiling), by = 1 ), 
                             y = rep(70.9 / 3 - 0.5, length(seq(round_any(min_x, 5, f = floor), 
                                                                   round_any(max_x, 5, f = ceiling), by = 1 )) ), 
                             xend = seq(round_any(min_x, 5, f = floor), round_any(max_x, 5, f = ceiling), by = 1 ), 
                             yend = rep(70.9 / 3 + 0.5, length(seq(round_any(min_x, 5, f = floor), 
                                                                   round_any(max_x, 5, f = ceiling), by = 1 ))) ), 
                         color = 'white') +
            geom_segment(aes(x = seq(round_any(min_x, 5, f = floor), round_any(max_x, 5, f = ceiling), by = 1 ), 
                             y = rep(70.8 / 3 + 18.5 / 3 - 0.5, length(seq(round_any(min_x, 5, f = floor), 
                                                                   round_any(max_x, 5, f = ceiling), by = 1 )) ), 
                             xend = seq(round_any(min_x, 5, f = floor), round_any(max_x, 5, f = ceiling), by = 1 ), 
                             yend = rep(70.8 / 3 + 18.5 / 3 + 0.5, length(seq(round_any(min_x, 5, f = floor), 
                                                                   round_any(max_x, 5, f = ceiling), by = 1 ))) ), 
                         color = 'white') +xlim(0,120)  + theme_void() + theme(legend.position = "none") + 
            scale_fill_gradient(low = "darkturquoise", high = "mediumorchid2", limits = limits, oob = scales::squish)
        }
        if (feature_name == "Offense Position" | feature_name == "Defense Position") {
          p <- ggplot() + ggtitle(feature_name) +
            geom_raster(data = data.frame(expand.grid(x=seq(0, 120), y=seq(0, 54))), aes(x = x, y = y), fill = "darkturquoise") +
            geom_point(data=feature_data %>% mutate(x = x+1, y=y+1) %>% filter(value !=0), 
                       aes(x = x, y = y), color = 'mediumorchid2',shape =15, size= 3) +
              geom_vline(aes(xintercept = seq(round_any(min_x, 5, f = floor), 
                                            round_any(max_x, 5, f = ceiling), by = 5)), 
                       color = 'white') +
            geom_segment(aes(x = seq(round_any(min_x, 5, f = floor), round_any(max_x, 5, f = ceiling), by = 1 ), 
                             y = rep(70.9 / 3 - 0.5, length(seq(round_any(min_x, 5, f = floor), 
                                                                   round_any(max_x, 5, f = ceiling), by = 1 )) ), 
                             xend = seq(round_any(min_x, 5, f = floor), round_any(max_x, 5, f = ceiling), by = 1 ), 
                             yend = rep(70.9 / 3 + 0.5, length(seq(round_any(min_x, 5, f = floor), 
                                                                   round_any(max_x, 5, f = ceiling), by = 1 ))) ), 
                         color = 'white') +
            geom_segment(aes(x = seq(round_any(min_x, 5, f = floor), round_any(max_x, 5, f = ceiling), by = 1 ), 
                             y = rep(70.8 / 3 + 18.5 / 3 - 0.5, length(seq(round_any(min_x, 5, f = floor), 
                                                                   round_any(max_x, 5, f = ceiling), by = 1 )) ), 
                             xend = seq(round_any(min_x, 5, f = floor), round_any(max_x, 5, f = ceiling), by = 1 ), 
                             yend = rep(70.8 / 3 + 18.5 / 3 + 0.5, length(seq(round_any(min_x, 5, f = floor), 
                                                                   round_any(max_x, 5, f = ceiling), by = 1 ))) ), 
                         color = 'white')+ theme(legend.position = "none") + xlim(0,120) + ylim(0, 54)  + theme_void() 
        }
        plot_list[[iter]] <- p
        iter = iter+1
      }
      arranged_plots <- ggarrange(plotlist = plot_list, ncol = 2, nrow = 4)
      print(arranged_plots)
      print(paste0("Frame ", i))
      ani.pause()}
    },movie.name="main_tackles_features.gif",ani.width = 600, ani.height = 600)
} 
```

```{r}
game_id=2022102700
play_id=3145

plot_combine_play_contribution(game_id, play_id)
plot_play(game_id, play_id)
plot_features(game_id, play_id)

tracking

pred_df
```






```{r}
plays %>% filter(playId==1948)

games %>% filter(gameId==2022103003)
```








```{r}
pred_df <- read.csv(paste0("/Users/nickbachelder/Desktop/Personal Code/Kaggle/Tackles/", game_id, "_", play_id, ".csv")) %>% dplyr::select(-X) %>%
      mutate(x = as.numeric(x), y = as.numeric(y))
pred_df %>% filter(omit==45287) %>%
  left_join(pred_df %>% filter(omit==0) %>% dplyr::select(frameId,exp_eop) %>% 
              dplyr::rename(exp_eop_orig = exp_eop)) %>% dplyr::select(frameId, exp_eop, exp_eop_orig, exp_contribution) %>% distinct()

pred_df %>% filter(frameId == 6, omit == 0) %>% filter(prob > 0.05)

pred_df %>% filter(omit == 0, frameId == 7) %>% ggplot() + geom_tile(aes(x= x, y=y, fill=prob))
```




$$\begin{bmatrix}
    \begin{bmatrix} \mu_{x1}& \mu_{y1} \end{bmatrix} \\
    . \\
    .\\
     \begin{bmatrix}  \mu_{xK}& \mu_{yK} \end{bmatrix}   \\
\end{bmatrix} $$

$$\begin{bmatrix}
    \begin{bmatrix}
    \sigma_{x1} & 0 \\
    0 & \sigma_{y1}   \\
\end{bmatrix} \\
. \\
. \\
     \begin{bmatrix}
    \sigma_{xK}& 0 \\
     0 & \sigma_{yK}   \\
\end{bmatrix}   \\
\end{bmatrix} $$

$$\begin{bmatrix}
    p{1}\\
    . \\
    . \\
     p{K}   \\
\end{bmatrix} $$


$$f(\text{End of Play}_i = \begin{bmatrix} x \\ y \end{bmatrix}) = \sum_{k=1}^{K}p_i \cdot \text{Normal}( \begin{bmatrix} x \\ y \end{bmatrix} ; \mu = \begin{bmatrix} \mu_{xk} \\ \mu_{yk} \end{bmatrix}, \Sigma = \begin{bmatrix}
    \sigma_{xk}& 0 \\
     0 & \sigma_{yk}   \\
\end{bmatrix})  $$


$$\text{Pixel}_{i, k} = \sum_{p \in {(\text{Players})}} \frac{S_{X,i}}{(\text{Distance From Grid Point}) \cdot (\text{Player Distance From Ball})} $$




$$\text{Ensemble of GMM} = \sum_m^M  \sum_k^K \frac{p_{km}}{M}\cdot \text{Normal}( \begin{bmatrix} x \\ y \end{bmatrix} ; \mu = \begin{bmatrix} \mu_{xkm} \\ \mu_{ykm} \end{bmatrix}, \Sigma = \begin{bmatrix}
    \sigma_{xkm}& 0 \\
     0 & \sigma_{ykm}   \\
\end{bmatrix}) = \text{New GMM with Redefined Mixture Probabilities} \\ \text{ where m = 'Model #' and k = 'Mixture # in original model'}$$


$$\text{TackleNet Weighted Loss } = \sum_{i\in \text{Batch Size}}^B  \left[
-\mathbf{w_i} \cdot LogSumExp_k^K \left( log(p_k)+LogLik(\text{Normal}( \begin{bmatrix} x \\ y \end{bmatrix} ; \mu = \begin{bmatrix} \mu_{xk} \\ \mu_{yk} \end{bmatrix}, \Sigma = \begin{bmatrix}
    \sigma_{xk}& 0 \\
     0 & \sigma_{yk}   \\
\end{bmatrix})\right)
\right] \\ \text{ where } \mathbf{w_i} = \frac{1}{\sqrt{(\text{End of Play Gain})_i}}, \text{ } k = \text{Mixture Index}, i = \text{Batch Index}$$




### Contribution analysis


```{r}
contribution_df <- read.csv(here::here("data/contribution_df_limit.csv")) 

ggplot(data=contribution_df) + geom_density(aes(x=estimated_contribution))

cumulative_contribution_df <- contribution_df %>% arrange(play_id) %>%
  group_by(nflId, displayName, position) %>% 
  mutate(overall_frame_id = row_number(), 
         cum_contribution = cumsum(estimated_contribution), 
         avg_contribution= mean(estimated_contribution),
         final_cum_contribution = cum_contribution[overall_frame_id == max(overall_frame_id)],
         total_frame_num = max(overall_frame_id)) %>% ungroup()

eys_rank <- cumulative_contribution_df %>% dplyr::select(nflId, displayName, position, final_cum_contribution) %>% distinct() %>%
  mutate(rank_cum_contribution = rank(-final_cum_contribution)) %>% 
  arrange(rank_cum_contribution) %>% 
  mutate(best = ifelse(rank_cum_contribution < 310, 1, 0))

final_eys <- cumulative_contribution_df %>% dplyr::select(nflId, displayName, position, overall_frame_id, final_cum_contribution) %>% 
  group_by(nflId, displayName, position) %>% filter(overall_frame_id == max(overall_frame_id)) %>% ungroup() %>% 
  left_join(eys_rank %>% dplyr::select(nflId, displayName, best) %>% distinct(), on = c("nflId", "displayName")) %>%
  filter(best == 1)

cumulative_contribution_df %>% left_join(eys_rank, on = c('nflId', 'displayName', 'position', 'final_cum_contribution'))  %>%
  ggplot() + 
  geom_line(aes(x = overall_frame_id, y = cum_contribution, group = nflId, alpha = best)) +
  geom_text_repel(data = final_eys, aes(x = overall_frame_id, y = final_cum_contribution, label=displayName), color = "blue") +
  theme_classic() + ggtitle("Cumulative Expected Yards Saved") + xlab("Play Number") + ylab("Cumulative Expected Yards Saved (EYS)")
```


```{r}
cumulative_contribution_df %>% dplyr::select(nflId, displayName, position, final_cum_contribution) %>%
  ggplot(aes(x = position, y = final_cum_contribution)) + geom_violin() + theme_classic()
  

general_table <- cumulative_contribution_df  %>% 
  dplyr::select(nflId, displayName, position, final_cum_contribution, avg_contribution, total_frame_num) %>% distinct() %>%
  mutate(rank_cum_contribution = rank(-final_cum_contribution), rank_avg_contribution = rank(-avg_contribution)) %>%
  arrange(rank_cum_contribution) 

general_table %>% filter(rank_cum_contribution < 10)  %>% gt() %>% gt_theme_538()
general_table %>% filter(rank_avg_contribution < 10)  %>% gt() %>% gt_theme_538()

general_table %>% ggplot() + geom_point(aes(x = total_frame_num, y = avg_contribution))
```




```{r}
max_df <- contribution_df%>% group_by(game_id, play_id, nflId) %>%
  mutate(max_contribution = max(estimated_contribution)) %>% 
  dplyr::select(nflId, displayName, position, max_contribution) %>%
  distinct() %>% 
  ungroup()%>%
  group_by(nflId, displayName, position) %>%
  dplyr::summarise(avg_max_contribution = mean(max_contribution)) %>%
  ungroup() %>%
  arrange(-avg_max_contribution) %>%
  mutate(percentile = percent_rank(avg_max_contribution))

plot(max_df$avg_max_contribution)

w_contracts <- max_df %>% left_join(contracts, on = "displayName") %>%
  left_join(
    tackles %>% dplyr::select(nflId, tackle, assist, forcedFumble) %>% 
      distinct() %>% group_by(nflId) %>% dplyr::summarise(total_tackle_involvement = sum(tackle, assist, forcedFumble)) %>% ungroup(),
    on = c("nflId")) %>%
  mutate(position = case_when(position %in% c("SS", "FS") ~ "S",
                              position %in% c("DT", "T", "NT") ~ "T",
                              position %in% c("ILB", "MLB", "DB") ~ "LB",
                              TRUE ~position))

w_contracts %>% filter(position != "CB") %>%
  ggplot(aes(x = avg_max_contribution, y = apy_cap_pct*100)) + geom_point() +
  geom_smooth(meathod = "lm") + 
  stat_cor(method = "pearson", label.x = 0, color = "red")  +
  facet_wrap(~position, scales = "free") + theme_classic()


w_contracts %>% filter(position != "CB")  %>%
  ggplot(aes(x = avg_max_contribution, y = total_tackle_involvement)) + geom_point() +
  geom_smooth(meathod = "lm") + 
  stat_cor(method = "pearson", label.x = 0, color = "red")  +
  facet_wrap(~position, scales = "free") + theme_classic()

w_contracts %>% filter(position != "CB")  %>% filter(!is.na(apy_cap_pct), !is.na(apy_cap_pct)) %>%
  ggplot(aes(x = total_tackle_involvement, y = apy_cap_pct*100)) + geom_point() +
  facet_wrap(~position, scales = "free") + theme_classic()
```




### Loss DF



```{r}
loss_df <- read.csv("/Users/nickbachelder/Desktop/Personal Code/Kaggle/Tackles/test_loss_track.csv") 

loss_df %>% filter(frames_from_eop == 3)
  
```








### SOI analysis 

```{r}
ggplot(data=contribution_df) + geom_density(aes(x=estimated_soi))

cumulative_contribution_df <- contribution_df %>% arrange(play_id) %>%
  group_by(nflId, displayName, position) %>% 
  mutate(overall_frame_id = row_number(), 
         cum_contribution = cumsum(estimated_soi), 
         avg_contribution= mean(estimated_soi),
         final_cum_contribution = cum_contribution[overall_frame_id == max(overall_frame_id)],
         total_frame_num = max(overall_frame_id)) %>% ungroup()

eys_rank <- cumulative_contribution_df %>% dplyr::select(nflId, displayName, position, final_cum_contribution) %>% distinct() %>%
  mutate(rank_cum_contribution = rank(-final_cum_contribution)) %>% 
  arrange(rank_cum_contribution) %>% 
  mutate(best = ifelse(rank_cum_contribution < 310, 1, 0))

final_eys <- cumulative_contribution_df %>% dplyr::select(nflId, displayName, position, overall_frame_id, final_cum_contribution) %>% 
  group_by(nflId, displayName, position) %>% filter(overall_frame_id == max(overall_frame_id)) %>% ungroup() %>% 
  left_join(eys_rank %>% dplyr::select(nflId, displayName, best) %>% distinct(), on = c("nflId", "displayName")) %>%
  filter(best == 1)

cumulative_contribution_df %>% left_join(eys_rank, on = c('nflId', 'displayName', 'position', 'final_cum_contribution'))  %>%
  ggplot() + 
  geom_line(aes(x = overall_frame_id, y = cum_contribution, group = nflId, alpha = best)) +
  geom_text_repel(data = final_eys, aes(x = overall_frame_id, y = final_cum_contribution, label=displayName), color = "blue") +
  theme_classic() + ggtitle("Cumulative Expected Yards Saved") + xlab("Play Number") + ylab("Cumulative Expected Yards Saved (EYS)")
```


```{r}
cumulative_contribution_df %>% dplyr::select(nflId, displayName, position, final_cum_contribution) %>%
  ggplot(aes(x = position, y = final_cum_contribution)) + geom_violin() + theme_classic()
  

general_table <- cumulative_contribution_df  %>% 
  dplyr::select(nflId, displayName, position, final_cum_contribution, avg_contribution, total_frame_num) %>% distinct() %>%
  mutate(rank_cum_contribution = rank(-final_cum_contribution), rank_avg_contribution = rank(-avg_contribution)) %>%
  arrange(rank_cum_contribution) 

general_table %>% filter(rank_cum_contribution < 10)  %>% gt() %>% gt_theme_538()
general_table %>% filter(rank_avg_contribution < 10)  %>% gt() %>% gt_theme_538()

general_table %>% ggplot() + geom_point(aes(x = total_frame_num, y = avg_contribution))
```




```{r}
min_df <- contribution_df%>% group_by(game_id, play_id, nflId) %>%
  mutate(min_soi = min(estimated_soi)) %>%  ungroup() %>%
  dplyr::select(nflId, displayName, position, min_soi) %>%
  distinct()  %>%
  left_join(
    tackles %>% dplyr::select(gameId, playId, nflId, tackle, assist, forcedFumble) %>% dplyr::rename(game_id = gameId, play_id = playId),
    on = c("game_id", "play_id", "nflId")) %>%
  mutate(position = case_when(position %in% c("SS", "FS") ~ "S",
                              position %in% c("DT", "T", "NT") ~ "T",
                              position %in% c("ILB", "MLB", "DB") ~ "LB",
                              TRUE ~position)) %>%
  mutate(tackle_involvement = ifelse(tackle >0 | assist >0 | forcedFumble > 0, 1, 0)) %>%
  mutate(min_soi_field_percent = min_soi / (54*120))

glm(data = min_df, formula = as.factor(tackle_involvement) ~ min_soi_field_percent, family = "binomial") %>% summary()
```














